# Generated by Django 6.0.3 on 2026-04-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_membership_role'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='supplier',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['organization', 'name'], name='suppliers_s_organiz_f6fc20_idx'),
        ),
    ]
