# Generated by Django 6.0.3 on 2026-04-01 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_membership_role'),
        ('suppliers', '0002_alter_supplier_options_supplier_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='organizations.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('organization', 'name')},
        ),
    ]
