# Generated by Django 6.0.3 on 2026-04-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=100)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('total_time', models.FloatField(db_index=True)),
                ('db_time', models.FloatField()),
                ('db_queries', models.IntegerField()),
                ('slow_queries', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-total_time'],
                'indexes': [models.Index(fields=['endpoint', 'created_at'], name='observabili_endpoin_5a13e5_idx')],
            },
        ),
    ]
