# Generated by Django 6.0.3 on 2026-04-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_transit', 'En tránsito'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
    ]
