# Generated by Django 6.0.3 on 2026-04-01 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('organizations', '0002_alter_membership_role'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='stockitem',
            name='inventory_s_product_37761c_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockitem',
            name='inventory_s_quantit_76b147_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockitem',
            name='inventory_s_product_298a54_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['organization', 'name'], name='inventory_l_organiz_b1125b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'created_at'], name='inventory_o_organiz_3e07ce_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['organization', 'order'], name='inventory_o_organiz_fcf8f9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['organization', 'product'], name='inventory_s_organiz_edca4b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['organization', 'location'], name='inventory_s_organiz_830629_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'created_at'], name='inventory_s_organiz_52d5aa_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['organization', 'created_at'], name='inventory_s_organiz_dcc873_idx'),
        ),
    ]
