# Generated by Django 6.0.3 on 2026-03-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_order_status_alter_stockmovement_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='min_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
