# Generated by Django 6.0.3 on 2026-04-01 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_location_options_alter_order_options_and_more'),
        ('organizations', '0002_alter_membership_role'),
        ('products', '0002_alter_product_options_product_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='organizations.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('organization', 'product', 'location')},
        ),
    ]
