# Generated by Django 6.0.3 on 2026-04-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransfer_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stocktransfer',
            name='unique_transfer_idempotency_per_org',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
