# Generated by Django 6.0.3 on 2026-04-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_location_organization_alter_order_organization_and_more'),
        ('organizations', '0002_alter_membership_role'),
        ('products', '0003_alter_product_organization_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stocktransfer',
            name='inventory_s_organiz_dcc873_idx',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'idempotency_key'], name='inventory_s_organiz_b25c33_idx'),
        ),
    ]
