# Generated by Django 6.0.3 on 2026-04-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_stocktransfer_inventory_s_organiz_dcc873_idx_and_more'),
        ('organizations', '0002_alter_membership_role'),
        ('products', '0003_alter_product_organization_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', None), _negated=True), fields=('organization', 'idempotency_key'), name='unique_movement_idempotency_per_org'),
        ),
    ]
