# Generated by Django 6.0.3 on 2026-03-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockmovement_options'),
        ('products', '0002_product_last_low_stock_alert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={},
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='min_stock',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['product', 'location'], name='inventory_s_product_37761c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['quantity', 'min_stock'], name='inventory_s_quantit_76b147_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['product', 'quantity'], name='inventory_s_product_298a54_idx'),
        ),
    ]
