# Generated by Django 6.0.3 on 2026-04-07 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockmovement_unique_movement_idempotency_per_org'),
        ('organizations', '0002_alter_membership_role'),
        ('products', '0003_alter_product_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', None), _negated=True), fields=('organization', 'idempotency_key'), name='unique_transfer_idempotency_per_org'),
        ),
    ]
