# Generated by Django 6.0.3 on 2026-04-08 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stocktransfer_unique_transfer_idempotency_per_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.order'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('order', 'Pedido'), ('transfer', 'Transferencia')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.stocktransfer'),
        ),
    ]
