# Generated by Django 6.0.3 on 2026-04-01 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_category_organization_and_more'),
        ('organizations', '0002_alter_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='organizations.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('organization', 'name')},
        ),
    ]
