# Generated by Django 6.0.3 on 2026-04-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('inventory:movement_created', 'Movimiento'), ('inventory:stock_low', 'Stock bajo'), ('inventory:product_risk', 'Producto en riesgo'), ('orders:updated', 'Pedido')], db_index=True, max_length=50),
        ),
    ]
