# Generated by Django 6.0.3 on 2026-04-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_importjob'),
        ('notifications', '0001_initial'),
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='seen',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'is_active'], name='notificatio_organiz_db5bec_idx'),
        ),
    ]
