# Generated by Django 6.0.3 on 2026-04-01 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_location_organization_alter_order_organization_and_more'),
        ('notifications', '0001_initial'),
        ('organizations', '0002_alter_membership_role'),
        ('products', '0003_alter_product_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'created_at'], name='notificatio_organiz_b709e0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'type'], name='notificatio_organiz_699081_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'seen'], name='notificatio_user_id_0709c4_idx'),
        ),
    ]
