# Generated by Django 6.0.3 on 2026-03-24 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_type_field'),
        ('products', '0002_product_last_low_stock_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='products.product'),
        ),
    ]
