# Generated by Django 6.0.3 on 2026-03-28 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockitem_min_stock'),
        ('notifications', '0003_alter_notification_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('movement', 'Movimiento'), ('stock_item_low', 'Incidencia almacén'), ('product_risk', 'Producto en riesgo'), ('order', 'Pedido'), ('alert', 'Alerta'), ('info', 'Información')], default='info', max_length=30),
        ),
    ]
