# Generated by Django 6.0.3 on 2026-03-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_location_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('critical', 'Crítica'), ('warning', 'Advertencia'), ('info', 'Info')], default='info', max_length=20),
        ),
    ]
