# Generated by Django 6.0.3 on 2026-03-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_stockitem_options_alter_stockitem_min_stock_and_more'),
        ('notifications', '0005_notification_priority'),
        ('products', '0002_product_last_low_stock_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('movement', 'Movimiento'), ('stock_item_low', 'Incidencia almacén'), ('product_risk', 'Producto en riesgo'), ('order', 'Pedido'), ('alert', 'Alerta'), ('info', 'Información')], db_index=True, default='info', max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['seen', '-created_at'], name='notificatio_seen_faf89a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', '-created_at'], name='notificatio_type_36f2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['product', 'type'], name='notificatio_product_4d41fe_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['location', 'type'], name='notificatio_locatio_8109a0_idx'),
        ),
    ]
