# Generated by Django 6.0.3 on 2026-03-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_low_stock_alert',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
