# Generated by Django 6.0.3 on 2026-04-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_category_organization_and_more'),
        ('organizations', '0002_alter_membership_role'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'name'], name='products_pr_organiz_f39bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'sku'], name='products_pr_organiz_88bfd9_idx'),
        ),
    ]
